# ========== SonarQube Project Configuration ==========
sonar.projectKey=Test   
sonar.projectName=Test
sonar.projectVersion=1.0

# 源代码目录（当前文件夹）
sonar.sources=.

# 排除不需要分析的文件夹（避免 node_modules 等）
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,public/**

# 编码格式
sonar.sourceEncoding=UTF-8

# SonarQube 服务器地址
sonar.host.url=http://localhost:9000

# 登录 Token
sonar.login=sqp_5afcdf9038d3d0ab4d116ac9047787813b4be15e
